[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uv run gunicorn -c gunicorn.conf.py 'app:create_app()'"
healthcheckPath = "/api/configs"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

